// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC32z10VXP8nYX30Fr5Lkw1MdKPxkyzXhk',
    appId: '1:998880925581:web:8570320fcd5f0ecf608fc4',
    messagingSenderId: '998880925581',
    projectId: 'billingapp-7d357',
    authDomain: 'billingapp-7d357.firebaseapp.com',
    storageBucket: 'billingapp-7d357.appspot.com',
    measurementId: 'G-5CXHHVL82Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2oxCaTYZOdI_QABbkw-4Q7XTpMdkNh40',
    appId: '1:998880925581:android:dc110d5f07c7f539608fc4',
    messagingSenderId: '998880925581',
    projectId: 'billingapp-7d357',
    storageBucket: 'billingapp-7d357.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4B4hU_uAcSm519-JEi7-38f570k8vSLI',
    appId: '1:998880925581:ios:4ba7924f48b93631608fc4',
    messagingSenderId: '998880925581',
    projectId: 'billingapp-7d357',
    storageBucket: 'billingapp-7d357.appspot.com',
    iosBundleId: 'com.example.billingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4B4hU_uAcSm519-JEi7-38f570k8vSLI',
    appId: '1:998880925581:ios:4ba7924f48b93631608fc4',
    messagingSenderId: '998880925581',
    projectId: 'billingapp-7d357',
    storageBucket: 'billingapp-7d357.appspot.com',
    iosBundleId: 'com.example.billingapp',
  );
}
